- src/yetibot/core/config.clj
- src/yetibot/core/init.clj
- display the full path to the expected file
- remind the user the problem may be in the 
content of the file (invalid .edn)
> Better error message when config not found/invalid

- config/config.sample.edn
- config/profiles.sample.clj
- src/yetibot/core/handler.clj
- test/yetibot/core/test/handler.clj
- Extracted the prefix match to a function
- Added configuration to allow custom prefixes
> Custom Prefix configuration

- project.clj
This will fix the "java.lang.Error: java.net.SocketTimeoutException:" issue when trying to run a Yetibot instance that connects to Slack behind a proxy
> Use gniazdo-jsr356

- src/yetibot/core/handler.clj
- src/yetibot/core/hooks.clj
- src/yetibot/core/repl.clj
Fix https://github.com/yetibot/yetibot/issues/731
> Prevent Yetibot from triggering itself

- src/yetibot/core/db/util.clj
I haven't tested this, just eyeballed it.
The only existing tests are for `combine-wheres` and did not extend.
> Added GROUP BY to db/util

- src/yetibot/core/adapters/adapter.clj
- src/yetibot/core/adapters/irc.clj
- src/yetibot/core/adapters/slack.clj
- src/yetibot/core/chat.clj
- src/yetibot/core/commands/category.clj
- src/yetibot/core/commands/channel.clj
- src/yetibot/core/commands/cron.clj
- src/yetibot/core/commands/that.clj
- src/yetibot/core/commands/users.clj
- src/yetibot/core/hooks.clj
- src/yetibot/core/interpreter.clj
- src/yetibot/core/models/channel.clj
- src/yetibot/core/models/history.clj
- src/yetibot/core/models/users.clj
- src/yetibot/core/repl.clj
- src/yetibot/core/webapp/resolvers.clj
- src/yetibot/core/webapp/routes/api.clj
- test/yetibot/core/test/adapters/irc.clj
- test/yetibot/core/test/adapters/slack.clj
- test/yetibot/core/test/models/history.clj
hey guys,
here is the PR related to https://github.com/yetibot/yetibot/issues/799 : _Renaming the room command to channel_ :-)
So what do we have here :
- first of all, I have renamed the `room.clj` file to `channel.clj` for more accuracy and also because I assume that the new naming scheme will be based on _channel_ from now on.
- I have also extended the `Adapter` protocol by introducing a new `channels` function which (should be)/is  nothing more than alias to the existing `rooms` function and whose implementation should just point to the existing `rooms` function implementation, for any record implementing the `Adapter` protocol.
- I have also _renamed_ multiple auxiliary functions whose names were related to _room_ to instead use the word _channel_. Same thing for the _docstrings_. …
> Rename room command to channel

- resources/graphql-schema.edn
- src/yetibot/core/webapp/resolvers.clj
- src/yetibot/core/webapp/routes/graphql.clj
> Surface `karma' via GraphQL API

- resources/graphql-schema.edn
- src/yetibot/core/models/karma.clj
- src/yetibot/core/webapp/resolvers.clj
- test/yetibot/core/test/models/karma.clj
Now accepting limits on count of returned karma records for aggregate reports, in stead of hard coding to 10.  Our model defends the DB, forcing a range of 1 - 100.
Some new tests added to kick the tires of both reports.
> Add karma high-score and high-giver reports to GraphQL API

- src/yetibot/core/commands/collections.clj
Allows commands like:
```
!range 1 5 | xargs repeat %s echo :yetibot: | xargs join
```
e.g.
> Allow non-map results in xargs

- src/yetibot/core/interpreter.clj
- src/yetibot/core/util/format.clj
This prevents an error if previous-value was not a string, such as when
a command incorrectly returns a number, or `data` is used to extract some
number from a data structure which is then passed across a pipe
The error was:
```
java.lang.IllegalArgumentException: Don't know how to create ISeq from: java.lang.Long
```
> Convert `previous-value` to string before attempting to check `empty?` on it

- src/yetibot/core/commands/karma.clj
- src/yetibot/core/commands/karma/specs.clj
- src/yetibot/core/observers/karma.clj
- test/yetibot/core/test/commands/karma.clj
- test/yetibot/core/test/commands/karma/specs.clj
- test/yetibot/core/test/observers/karma.clj
We now always strip the `@` char when parsing messages.  All internal
representation uses the base user-id.
Closes #91
> Karma self-karma addition regression fix

- .travis.yml
- project.clj
- enables auto releases from master - [example build](https://travis-ci.com/yetibot/yetibot.core/jobs/201998647)
- derives version from timestamp and git sha1 e.g. `20190521.222441.b9df505`
Blog post about these changes and CD in general is forthcoming.
> Enable continuous delivery with git-derived version

- project.clj
- src/yetibot/core/adapters.clj
- src/yetibot/core/adapters/irc.clj
- src/yetibot/core/adapters/slack.clj
- src/yetibot/core/commands/duckling.clj
- src/yetibot/core/commands/karma.clj
- src/yetibot/core/commands/ssh.clj
- src/yetibot/core/commands/url.clj
- src/yetibot/core/db.clj
- src/yetibot/core/db/util.clj
- src/yetibot/core/handler.clj
- src/yetibot/core/init.clj
- src/yetibot/core/interpreter.clj
- src/yetibot/core/logging.clj
- src/yetibot/core/models/admin.clj
- src/yetibot/core/models/channel.clj
- src/yetibot/core/models/default_command.clj
- src/yetibot/core/models/mail.clj
- src/yetibot/core/parser.clj
- src/yetibot/core/repl.clj
- src/yetibot/core/schema.clj
- src/yetibot/core/spec.clj
- src/yetibot/core/util/command.clj
- src/yetibot/core/util/config.clj
- test/yetibot/core/test/adapters/irc.clj
- test/yetibot/core/test/adapters/slack.clj
This is a first stab at migrating to clojure.spec. I wouldn't call it ready to be merged but thought it would be a good idea to get feedback early.
> Switch from schema to clojure.spec

- project.clj
- src/yetibot/core/adapters/irc.clj
Allow 1 request per second with burstiness up to 5.
Use log/warn when server reports flooding.
Seems that 1 rps is the default setting for IRC protocol. I've played with different throttling strategies on freenode using `!range 20 | xargs echo` and seems that current one is pretty safe.
> Throttle send-msg for IRC to prevent flooding.

- src/yetibot/core/adapters/irc.clj
- test/yetibot/core/test/adapters/irc.clj
irclj uses separate thread for connection. Whenever "nick in use" occurs it calls callback and then throws Exception which stops the thread. (https://github.com/Raynes/irclj/blob/f230935cd94dc1c86ffb6677c1b6bb8675d3df94/src/irclj/process.clj#L91)
So in order to recover this siutation I have to stop/start adapter.
> Handle "Nick in use" notice in IRC adapter.

- project.clj
Hey @devth 
I just bumped `org.clojure/data.xml` to accommodate `cognitect/aws-api`. I have aligned it with the version documented [here](https://github.com/cognitect-labs/aws-api/blob/master/deps.edn).
can you PTAL
thanks a lot ^^
> Bump org.clojure/data.xml dep version to accommodate cognitect/aws-api

- config/config.sample.edn
- src/yetibot/core/logging.clj
This PR makes the _log file path_ configurable via the external `config.edn` file.
```
:log {:level "debug"
:path "/var/log/yetibot/yetibot.log"}
```
can you PTAL @devth 
thanks ;-)
> Make yetibot log file path configurable

- src/yetibot/core/commands/help.clj
- src/yetibot/core/hooks.clj
- src/yetibot/core/util/command.clj
- test/yetibot/core/test/util/command.clj
Fix https://github.com/yetibot/yetibot.core/issues/134
> Exclude help from white black lists

- src/yetibot/core/loader.clj
- test/yetibot/core/test/commands/cmd.clj
- test/yetibot/core/test/loader.clj
- added new midje tests for loader.clj
- replaced existing clojure.test with midje tests
- found an odd issue where namespaces were being "double loaded" because dups of namespaces were being returned via the `find-namespaces` function .. not entirely sure why, so running `(distinct)` over list before returning
- loading YB commands in `test/cmd.clj` because it needs them after removing said command from `test/loader.clj` via `clojure.test`
🤞 🤞
> tests for core.loader.clj and small change v0.2

- src/yetibot/core/loader.clj
- dropped non-used refs
- added some doc strings
- variablized regex related to "all" commands and observers
- used new regex vars to remove `(last)` logic in `(yetibot-all-namespaces)` << uncle bob would be proud
- small style changes in `(try)` << make kondo happy
- using `(doseq)` vs `(dorun)` for side effects << make codeclimate happy
- added comments and `(comment)`
> changes to loader.clj to make kondo/codeclimate more happy

- src/yetibot/core/config.clj
- src/yetibot/core/util/config.clj
- test/yetibot/core/test/config.clj
- using idiomatic `if-not`
- added arity/1 to `prefixed-env-vars` to allow for user defined env vars, mainly for testing .. arity/0 (original func signature) passes in `environ.core/env` to arity/1
- added arity/1 and arity/2 to `config-from-env-or-file` to allow for user defined file cfgs and env cfgs .. arity/0 (original func signature) passes in `load-edn!` and `prefixed-env-vars` to arity/2 -- which were previously in the body of the function
- added many `(comment)`
- added test for core/config.clj
not sure how you are going to feel about me modifying the arity of those functions .. it won't hurt my feelings if you want to reject, i am just trying to find a "pure" way i can test these functions that don't rely on environmental factors ..
> mods to core/config.clj and added test for it

- src/yetibot/core/db/util.clj
- test/yetibot/core/test/db/util.clj
- pulled creation of SQL query string out of main `(query)` function
- generate SQL query string in new `(generate-sql-query)` function
- call new "generate" function from original "query" function
- inline get of `:query/identifiers`
- added `(comment)` to excercise code
- added tests for new `(generate-sql-query)` function, both simple and complex
i hope i am not being petty here .. i just like to be able to see/test the generated SQL before i actually use it .. i also get the generation of the SQL string is pretty simple, but there is real logic/transformation there that might be good to test
i decided to destructure in the `(let)` vs the function args so my editor is happy when viewing function docs
> extract generation of SQL query string from query map to allow for testing of generated statements

- project.clj
- src/yetibot/core/models/admin.clj
- src/yetibot/core/models/help.clj
- test/README.md
- test/yetibot/core/test/models/admin.clj
- test/yetibot/core/test/models/help.clj
- added `(comment)` and doc strings to models/admin
- expanded to arity/2 for 2 functions in models/admin to allow for testing,, original function signatures (arity/1) passes in `(config)` to expanded arity/2
- destructuring in `(let)` for `(user-is-admin?)` arity/2 to make editor happy when retrieving doc string
- made kondo happy for models/help, as well as added doc string for `(remove-docs)`
- updated test/README for some REPL pointers when wanting to exercise code that relies on instance config
- added midje tests for models/admin
- migrated tests for models/help to midje, as well as adding one more
FYI -- i "fixed" and committed the tests with `lein cljfmt` -- to see what the result would be .. didn't want to assume "this is the way", so did not commit plugin to `project.clj` -- but …
> small updates to models/(admin|help), added testing for models/admin, migrated testing for models/help to midje

- test/yetibot/core/test/handler.clj
- test/yetibot/core/test/parser.clj
- test/yetibot/core/test/util/command.clj
- moved tests around for `core/handler`, `core/parser`, and `core/util/command`
- some general cleanup
- made kondo happy
event tho local tests are working AOK, i expect initial GH test action to fail due to "race condition" concerning the loading of commands .. i believe this is because midje is either running tests in parallel and/or midje `facts` are ran in isolation << a little odd tho `lein test` runs locally without fail
will most likely require mod to each test file to include `core/loader/load-commands` .. will fix as needed
> re-org test code so NSs are being tested in the related test file

- src/yetibot/core/adapters/adapter.clj
- src/yetibot/core/util/format.clj
- test/yetibot/core/test/adapters.clj
- test/yetibot/core/test/adapters/adapter.clj
- test/yetibot/core/test/util/format.clj
- removed all refs to `clojure.test` for tests in question
- simple kondo fixes for `src/yetibot/core/util/format.clj`
- better test setup for `test/yetibot/core/test/adapters.clj`
- better test teardown and mocking for `test/yetibot/core/test/adapters/adapter.clj`
- re'org and added tests for `test/yetibot/core/test/util/format.clj`
not the most meaningful PR -- but better use of and one step closer for the `midje` migration
> improved linting, better test setup/teardown, re'org and added tests

- src/yetibot/core/commands/alias.clj
- test/yetibot/core/test/commands/alias.clj
- `src/yetibot/core/commands/alias.clj`
- small kondo cleanup changes by dropping refs and unused "vars"
- made more idiomatic by using `(run!)` vs `(dorun (map))`
- `test/yetibot/core/test/commands/alias.clj`
- migrated to midje
- added new tests << including some privates
not curing cancer with this one -- but small move to having midje everywhere
i think codecov is going to yell at me because i made a change to src `(load-aliases)` without adding tests << is minor and hard to truly test because of side-effects
> migrate to midje for core.commands.alias

- src/yetibot/core/commands/decode.clj
- test/yetibot/core/test/commands/decode.clj
- `src/yetibot/core/commands/decode.clj`
- a simple kondo quieting of a supposed "unused import"
- `test/yetibot/core/test/commands/decode.clj`
- migration to midje only .. no new tests
> migrate tests to midje and small kondo cleanup

- src/yetibot/core/commands/observe.clj
- test/yetibot/core/test/commands/observe.clj
- `src/yetibot/core/commands/observe.clj`
- did some kondo cleaning
- made changes to `(if-let)` to `(when-let)` because codeclimate said it is more idio than returning `nil` for logical false
- made changes to `(dorun (map))` to `(run!)` because codeclimate said it is more idio
- `test/yetibot/core/test/commands/observe.clj`
- migrated tests to midje and added one, non-amazing test
> migrate to midje for core.commands.observe and some kondo/codeclimate cleaning

- project.clj
- src/yetibot/core/models/history.clj
- test/README.md
- test/yetibot/core/test/models/history.clj
- `project.clj`
- added kibit to plugins
- `src/yetibot/core/models/history.clj`
- some kondo cleaning of unused refs and "vars"
- small change to `(not=)` vs `(not (=))`
- `test/README.md`
- update on how to use kibit locally
- `test/yetibot/core/test/models/history.clj`
- migrate to midje
- i think this is THE LAST of real use of clojure.test in core 🥳 🎈 👯 🕺 
- ^^ minus one use of `(function?)` on a return type
> migrate to midje for core.models.history and some kondo/kibit cleaning

- src/yetibot/core/adapters/slack.clj
- test/yetibot/core/test/adapters/slack.clj
- `src/yetibot/core/adapters/slack.clj`
- no change in behavior, function still returns `nil` since logging is the last action
- extracted the send-msg options merge into own function
- `->send-msg-options` naming comes from "elements of clojure" recommendation on how to name transforms
- extracted logging of send-msg into own function
- it appears both log actions are not dependent on ordering, so put into one
- motivation comes from [LINK](https://kumarshantanu.medium.com/organizing-clojure-code-with-functional-core-imperative-shell-2f2ee869faa2)
- `send-msg` becomes "workflow", while "core" is the creation of message options
- `test/yetibot/core/test/adapters/slack.clj`
- you will see more meaningful tests for `send-msg`
- new functions have their own tests
as always, very open to …
> small refactor of core.adapters.slack/send-msg

- src/yetibot/core/handler.clj
- test/yetibot/core/test/handler.clj
- `src/yetibot/core/handler.clj`
- kondo clean unused refs and bindings
- extracted creation of correlation id `(->correlation-id)` into its own function and added tests
- extracted the "parsing" of the message body `(->parsed-message-info)` into its own function and added tests
- extracted the adding of a user's message to history `(add-user-message-to-history)` into its own function and added tests
- used newly extracted functions to create let bindings
- used newly extracted function to add user message to history
- verified at DB level history is being added as expected (see below)
- kibit change to use `(not=)` vs `(not (=))`
- `test/yetibot/core/test/handler.clj`
- kondo clean unused refs and bindings
- added tests for newly created functions
*SIDE NOTE:* this is step 1 of …
> refactor of adding user message to history table

- src/yetibot/core/handler.clj
- test/yetibot/core/test/handler.clj
- `src/yetibot/core/handler.clj`
- extracted into `(->handled-expr-info)` logic transforming handled expr result into useful info map to be used by other functions
- extracted into `(add-bot-response-to-history)` logic recording bot response to history table when option is enabled
- extracted into `(->handled-expr-results)` logic transforming handled expr results into useful collection to be returned by function
- modified `(record-and-run-raw)` to use new functions and kondo-cleaned where recommended
- extracted into `(dispatch-command-response)` logic dispatching response to be formatted, and ultimately passed long to `send-message`
- modified `(handle-raw)` to use new functions
- `test/yetibot/core/test/handler.clj`
- created tests for newly extracted functions
verified at DB level …
> refactor of adding bot response to history table

- src/yetibot/core/logging.clj
- test/yetibot/core/test/logging.clj
- `src/yetibot/core/logging.clj`
- kondo-cleaned used refs
- switched `(def log-path-config ..)` into `(defn log-path-config ..)` and added ref to default log path var
- ^^ double checked YB.core and YB repos to make sure no other refs to var exist
- `test/yetibot/core/test/logging.clj`
- added tests everywhere
i know not super important, but i was bored and wanted something ez to work on
> ez friday win - tests for YB.core.logging

- src/yetibot/core/adapters.clj
- test/yetibot/core/test/adapters.clj
- `src/yetibot/core/adapters.clj`
- added transform function `(->registerable-adapter)` for related logic
- updated `(register-adapters!)` to use new transform
- `test/yetibot/core/test/adapters.clj`
- simply added some more tests, nothing earth shattering
> for YB.core.adapters, small change to src and added test

- .gitignore
- src/yetibot/core/chat.clj
- test/yetibot/core/test/chat.clj
- added a new gitignore for `.clj-kondo` -- appears when adding said vscode extension
- `yetibot.core.chat`
- exposed `validate-sender` function so i can test it
- `yetibot.core.test.chat`
- expanded on tests for `should-send-msg-for-each?`, mainly asserting the negative
- added tests for `validate-sender`, a little funky since said function returns a function, so really just testing the returned function
i am bored and wanted to exercise these muscles a little
> added additional tests for yb.core.chat

- test/yetibot/core/test/chat.clj
- test/yetibot/core/test/parser.clj
- `test/yetibot/core/test/chat.clj`
- nothing earth-shattering, just thought i would increase test coverage
- required some london school (interaction testing) to get things to working just enough to return a useable/testable result
- `test/yetibot/core/test/parser.clj`
- noticed there was a syntax error in the tests for YB.core.parser -- so i fixed it
- i guess midje is "smart enough" to just ignore these kinds of errors rather than throw an exception
> added tests for YB.core.chat and fixed syntax for tests related to YB.core.parser

- src/yetibot/core/util/format.clj
- test/yetibot/core/test/util/format.clj
- `src/yetibot/core/util/format.clj`
- dropped function `format-data-as-string`
- check both YB and core and didn't see any reference to it -- so think it is safe
- `test/yetibot/core/test/util/format.clj`
- added some additional tests for YB.core.util.format
- nothing earth shattering, just thought i tease out the `format-data-structure` function to see what it would do in various conditions
- also added test for `format-exception-log`
!! IT'S 🍟 DAY !!
> removed unused function, added tests for util.format

- test/yetibot/core/test/db.clj
- test/yetibot/core/test/parser.clj
oh-kay, here's the situation (<< name that tune)
i want to work on and test a specific NS, and only that NS .. when running tests for the 1st time in a clean environment (`docker-compose up -d` 1st run, no data, no previous runs of test), i get fails when ONLY testing that NS .. example ::
```bash
lein test yetibot.core.test.parser
...
...
22-04-20 19:40:03 GKS-MBP.local INFO [yetibot.core.interpreter:160] - reduce commands ([:cmd [:words "category" [:space " "] "names"]] [:cmd [:words "echo" [:space " "] "async:" [:space " "] [:sub-expr [:expr [:cmd [:words "render" [:space " "] "{{async}}"]]]]]])
22-04-20 19:40:03 GKS-MBP.local INFO [yetibot.core.db.util:194] - db query ["SELECT * FROM yetibot_channel WHERE chat_source_adapter=? AND chat_source_channel=?" "nil" nil]
FAIL about …
```
> loading of db schema and required commands for test NS

- src/yetibot/core/parser.clj
- test/yetibot/core/test/chat.clj
- test/yetibot/core/test/commands/cmd.clj
- test/yetibot/core/test/commands/render.clj
- test/yetibot/core/test/handler.clj
- test/yetibot/core/test/interpreter.clj
- test/yetibot/core/test/parser.clj
- test/yetibot/core/test/webapp/routes/graphql.clj
yes, major bikeshedding here, just trying to be more consistent and follow what kibit tells me
- `src/yetibot/core/parser.clj`
- kibit told me to do this
- dropping heavy `(load-commands)` for something "lighter" and/or declaring tested bot commands in `(:require)`
- `test/yetibot/core/test/commands/cmd.clj`
- `test/yetibot/core/test/commands/render.clj`
- `test/yetibot/core/test/handler.clj`
- `test/yetibot/core/test/interpreter.clj`
- `test/yetibot/core/test/webapp/routes/graphql.clj`
- `test/yetibot/core/test/parser.clj`
- no need for many uses of `(load-ns)` here, just use `(:require)`
> offload use of heavy `(load-commands)` and declare expected commands in `(:require)`

- src/yetibot/core/adapters/discord.clj
As @devth pointed out, we were not binding the chat `target` for the reactions. 
[fix #1123](https://github.com/yetibot/yetibot/issues/1123)
> fix: #1123 - Fixing issue with discord observors and reactions
