yetibot/core

.gitignore, src/yetibot/core/adapters/irc.clj, src/yetibot/core/adapters/slack.clj, src/yetibot/core/commands/users.clj, src/yetibot/core/db/history.clj, src/yetibot/core/models/history.clj, src/yetibot/core/models/users.clj, src/yetibot/core/observers/history.clj
This pull request has a few fixes/improvments:
* Added support for @ mentions in slack in both history and user list
* Reset conn atom in slack adapter on close
* Fix for NPE on closing a nonexistent IRC connection
* Added intellij files to .gitignore
=> Better slack support and minor cleanup

src/yetibot/core/adapters/slack.clj
Hello! Let me know if I need to make any changes.
=> Issue #483 Subscribe to slack message edit events and re-run commands

src/yetibot/core/adapters/adapter.clj, src/yetibot/core/adapters/irc.clj, src/yetibot/core/hooks.clj, src/yetibot/core/repl.clj
Fix devth/yetibot#644
Fix devth/yetibot#633
=> Bind *adapter* inside each irc event handler

.travis.yml, project.clj, src/yetibot/core/chat.clj, src/yetibot/core/commands/about.clj, src/yetibot/core/commands/collections.clj, src/yetibot/core/interpreter.clj, src/yetibot/core/repl.clj
=> Data across pipes #590

src/yetibot/core/commands/observe.clj, src/yetibot/core/db/observe.clj
=> Chan specific obs

project.clj
I tested this earlier, looks good.
=> Switch to the continuation of Raynes/tentacles

README.md, src/yetibot/core/init.clj, src/yetibot/core/repl.clj, src/yetibot/core/webapp/handler.clj
Fix https://github.com/yetibot/yetibot/issues/744
=> Configure and document remote nrepl usage

src/yetibot/core/commands/category.clj, src/yetibot/core/commands/collections.clj, src/yetibot/core/commands/reply_to.clj
@devth, I'm happy with this.  `xargs` didn't have any defined tests, and I've not improved that.  I can work on adding those in this PR, another, or just defer for now.
=> 750 preserve ordering in xargs

src/yetibot/core/db/util.clj
=> Added support for HAVING clause to y.c.db.util/query

src/yetibot/core/handler.clj, src/yetibot/core/parser.clj, src/yetibot/core/util/command.clj, test/yetibot/core/test/parser.clj
Fix https://github.com/yetibot/yetibot/issues/784
=> Expand value/error out of sub-expressions in instaparse transform

config/config.sample.edn, config/profiles.sample.clj, src/yetibot/core/init.clj
Hey fellows,
this PR implements yetibot/yetibot#596
I know this issue has been opened for years now but I had 5 minutes so ;-) ...
not sure if it's still relevant for you though but if it is then can you guys PTAL
thanks in advance
=> Make nrepl port configurable

.travis.yml, package-lock.json, project.clj, src/yetibot/core/commands/collections.clj, src/yetibot/core/config.clj, src/yetibot/core/init.clj, src/yetibot/core/repl.clj, src/yetibot/core/webapp/handler.clj, src/yetibot/core/webapp/routes/home.clj, test/yetibot/core/test/handler.clj
Ref https://github.com/yetibot/yetibot/issues/804
=> Clojure 1.10 upgrade

doc/CHANGELOG.md, package-lock.json, project.clj, src/yetibot/core/adapters/slack.clj
Fix https://github.com/yetibot/yetibot/issues/808
=> Improve Slack reconnection logic

project.clj, src/yetibot/core/adapters/slack.clj, src/yetibot/core/util.clj, test/yetibot/core/test/util.clj
Fix https://github.com/yetibot/yetibot/issues/820
=> Add blocks support for better image output

project.clj
=> Migrate yetibot.core tests to Midje, consistent with yetibot

doc/CHANGELOG.md, src/yetibot/core/adapters/slack.clj
Fix https://github.com/yetibot/yetibot/issues/868
=> Fix posting collections in Slack Threads

doc/CHANGELOG.md, src/yetibot/core/commands/collections.clj, src/yetibot/core/util/command_info.clj, test/yetibot/core/test/commands/collections.clj
Fix https://github.com/yetibot/yetibot/issues/862
=> Preserve data in data <path>

doc/CHANGELOG.md, src/yetibot/core/commands/!.clj, src/yetibot/core/commands/alias.clj, src/yetibot/core/commands/channel.clj, src/yetibot/core/commands/collections.clj, src/yetibot/core/commands/observe.clj, src/yetibot/core/commands/that.clj, src/yetibot/core/hooks.clj
Fix https://github.com/yetibot/yetibot/issues/806
=> Allow commands to specify multiple pairs of topic / regexes

config/config.sample.edn, config/profiles.sample.clj, src/yetibot/core/adapters/slack.clj, src/yetibot/core/commands/eval.clj, src/yetibot/core/commands/observe.clj, src/yetibot/core/hooks.clj, src/yetibot/core/models/admin.clj
Fix https://github.com/yetibot/yetibot/issues/925
=> Generalize concept of admin from eval to its own model and config

config/config.sample.edn, config/profiles.sample.clj, src/yetibot/core/commands/karma.clj, src/yetibot/core/commands/karma/specs.clj, test/yetibot/core/test/commands/karma.clj, test/yetibot/core/test/commands/karma/specs.clj
@devth I'll rebase to master after you merge #88
=>  Karma response emojis now configurable

src/yetibot/core/commands/alias.clj, src/yetibot/core/commands/help.clj, src/yetibot/core/models/help.clj, test/yetibot/core/test/models/help.clj
Fix https://github.com/yetibot/yetibot/issues/460
Related to https://github.com/yetibot/yetibot/issues/807
=> Store alias help docs separately from built in commands

src/yetibot/core/commands/collections.clj, src/yetibot/core/commands/decode.clj, src/yetibot/core/commands/render.clj, src/yetibot/core/interpreter.clj, src/yetibot/core/util/command_info.clj, test/yetibot/core/test/commands/collections.clj, test/yetibot/core/test/commands/decode.clj
Fix https://github.com/yetibot/yetibot/issues/803
=> Collections data propagation

doc/CATEGORIES.md, doc/COMMAND_HANDLING_PIPELINE.md, doc/CONFIGURATION.md, doc/LOADING.md
Documentation has some broken links.
=> fix broken links

src/yetibot/core/commands/history.clj, test/yetibot/core/test/commands/history.clj
Fix https://github.com/yetibot/yetibot/issues/948
=> Restrict private history in history command

doc/CHANGELOG.md
=> Add changelog for last two releases

src/yetibot/core/adapters/slack.clj, src/yetibot/core/commands/observe.clj
Fix https://github.com/yetibot/yetibot/issues/761
=> Reply in-thread for observers and in-thread message edits

config/config.sample.edn, config/profiles.sample.clj, project.clj, src/yetibot/core/adapters.clj, src/yetibot/core/adapters/adapter.clj, src/yetibot/core/adapters/mattermost.clj, src/yetibot/core/adapters/slack.clj, src/yetibot/core/commands/observe.clj, src/yetibot/core/loader.clj, src/yetibot/core/util.clj, test/yetibot/core/test/adapters/mattermost.clj, test/yetibot/core/test/models/history.clj
Fix https://github.com/yetibot/yetibot/issues/971
=> Add Mattermost adapter 📞

project.clj, src/yetibot/core/commands/karma.clj, src/yetibot/core/db/karma.clj, src/yetibot/core/models/karma.clj, src/yetibot/core/webapp/handler.clj, src/yetibot/core/webapp/resolvers.clj, test/yetibot/core/test/commands/karma.clj, test/yetibot/core/test/models/karma.clj
Fix https://github.com/yetibot/yetibot.core/pull/123
=> Make karma channel-local by default

src/yetibot/core/commands/karma.clj, src/yetibot/core/hooks.clj, src/yetibot/core/observers/karma.clj, test/yetibot/core/test/observers/karma.clj
Fix https://github.com/yetibot/yetibot/issues/1012
=> Ensure chat-source is propagated in emoji based karma obs

src/yetibot/core/hooks.clj, src/yetibot/core/models/channel.clj, src/yetibot/core/observers/karma.clj
Fix https://github.com/yetibot/yetibot/issues/1011
=> Disable karma obs by default and allow it to be enabled on a per-channel basis

.travis.yml
=> Avoid running tests twice

config/config.sample.edn, config/profiles.sample.clj, config/sample.env, src/yetibot/core/hooks.clj, src/yetibot/core/loader.clj, src/yetibot/core/util/command.clj, src/yetibot/core/webapp/route_loader.clj, test/yetibot/core/test/util/command.clj, tests.edn
Fix https://github.com/yetibot/yetibot/issues/988
=> Add command whitelist/blacklist support

config/profiles.sample.clj, doc/CHANGELOG.md, src/yetibot/core/commands/help.clj, src/yetibot/core/hooks.clj, src/yetibot/core/interpreter.clj
Fix https://github.com/yetibot/yetibot.core/issues/136
=> Fallback to default command handling when a command is disabled

doc/CHANGELOG.md, src/yetibot/core/commands/help.clj, src/yetibot/core/util/command.clj
Ref https://github.com/yetibot/yetibot.core/issues/136
=> Exclude aliases from white and black lists

config/config.sample.edn, config/profiles.sample.clj, config/sample.env, src/yetibot/core/commands/help.clj, src/yetibot/core/models/default_command.clj
Fix https://github.com/yetibot/yetibot.core/issues/139
=> Allow configurable fallback help text

src/yetibot/core/commands/my.clj, src/yetibot/core/db/my.clj, src/yetibot/core/hooks.clj
Fix https://github.com/yetibot/yetibot/issues/427
=> Add my command

src/yetibot/core/commands/category.clj, src/yetibot/core/hooks.clj
Fix https://github.com/yetibot/yetibot.core/issues/147
=> Only list enabled commands when listing commands for a category

project.clj, src/yetibot/core/config.clj, src/yetibot/core/logging.clj
Hey @ontanj, this should fix the logging config issue when running tests.
=> Configure logging when running tests

src/yetibot/core/commands/collections.clj, test/yetibot/core/test/commands/collections.clj
Add grep -v command and some tests.
Also fix a bug that gives overlapping matches for grep -C.
Fix issue yetibot/yetibot#980 in yetibot repo.
=> Add grep -v command

doc/adr/0001-record-architecture-decisions.md, doc/adr/0002-allow-dynamic-loading-of-yetibot-plugins-via-config.md, project.clj, src/yetibot/core/init.clj, src/yetibot/core/loader.clj, src/yetibot/core/repl.clj
Fix https://github.com/yetibot/yetibot/issues/1036
=> Dynamic modules

src/yetibot/core/hooks.clj, test/yetibot/core/test/hooks.clj
- was able to replace existing `clojure.test` with midje `facts`
- expanding what is being tested, primarily public functions that are in use by other namespaces
- bailed on some functions i do not yet understand
- made kondo mostly happy for `test/hooks.clj`
- yes, i am bored at work this week >> sorry
=> additional tests for `core/hooks.clj`

src/yetibot/core/hooks.clj, src/yetibot/core/util/config.clj, test/yetibot/core/test/hooks.clj, test/yetibot/core/test/util/config.clj
- core/hooks to use thread-last, easier to read
- comments for util/config
- new hooks/obs-hook test
- new tests for util/config
=> added tests for util/config and core/hooks, small mod to core/hooks, comments

src/yetibot/core/db/util.clj, test/README.md, test/yetibot/core/test/db/util.clj
- small kondo update to db/util.clj and added some comments
- migrated db/util.clj to midje tests
- added a couple of minor tests
- updated testing README for those seeking extra testingcredit
=> migrate db/util.clj to midje, make kondo happy where i can, update testing README

src/yetibot/core/config.clj, test/yetibot/core/test/config.clj
=> rollback increased arity for core.config/config-from-env-or-file and use mocks to test

src/yetibot/core/interpreter.clj, test/yetibot/core/test/interpreter.clj
attempt #2 of PR
over 300 tests now !!
=> added tests for YB.core.interpreter .. small changes to src to make kondo happy

src/yetibot/core/adapters/slack.clj, test/yetibot/core/test/adapters/slack.clj
- this is for YB.core.adapters.slack and its related tests
- please double check my changes to SRC from `(dorun (map))` to `(run!)` << trying to make codeclimate happy
- we don't have any tests in place for these given they are primarily side-effects, and while my local testing seems AOK, good to have extra eyes on this to make sure i am not missing something important
=> migrate tests to midje, add tests, code cleanup, small idiomatic changes to src

src/yetibot/core/models/channel.clj, test/README.md, test/yetibot/core/test/models/channel.clj
- added all new midje tests
- did some small kondo cleaning for src
- added readme for targeting a specific NS when running tests, vs running all
=> tests for YB.core.models.channel

src/yetibot/core/models/users.clj, test/yetibot/core/test/models/users.clj
- `src/yetibot/core/models/users.clj`
- dropped unused refs
- prefixed unused bindings with `_`
- `test/yetibot/core/test/models/users.clj`
- migrated all tests to midje
- added some tests
=> migrate tests to midje and some kondo cleanup

test/yetibot/core/test/models/status.clj
assuming the private functions i am replacing didn't do anything, this should be an easy one
^^ famous last words
=> migrate to midje for core.models.status

test/yetibot/core/test/adapters/slack.clj
soooo -- let's talk about this one .. i am not sure how you are going to feel about it because there is A LOT of london school of TDD (verify function X is called with params Y and Z) vs chicago school (function X returns Y) ..
i tried to find a nice balance and implement chicago school wherever i could -- but since a lot of these tests are on things that have real side causes/effects -- i felt like i had little choice but go to london ..
that said, i started down the road of refactoring AND adding tests -- but that felt dirty to me, since i don't like to touch things unless it has a test, or is very small change .. my follow up would be to add the refactors i have in mind, to ensure i am not breaking functionality ..
happy thursday !!
=> added tests for slack adapter

src/yetibot/core/adapters/slack.clj, test/yetibot/core/test/adapters/slack.clj
- `src/yetibot/core/adapters/slack.clj`
- many recommendations made by clj-kondo to drop unused libs, refs, and bindings
- added some docstrings
- performed integration test using new core binary and did not see any wild errors when joining channel, leaving channel, sending messages, etc
- simplecov may yell at me because i made changes in functions that have no tests
- `test/yetibot/core/test/adapters/slack.clj`
- added a couple of tests
=> kondo cleaning and additional tests for the slack adapter

test/yetibot/core/test/chat.clj
only a couple of tests, nothing else
i had to get something in because i felt guilty for not submitting anything at all last week .. what a slacker !!
=> a couple of tests for YB.core.chat

test/yetibot/core/test/chat.clj
no src file changes, all new tests
learned how to use `:times` in midje `(provided)`, as well as using checkers within prereqs
=> more tests for YB.core.chat

.github/workflows/release.yml, .github/workflows/test.yml, project.clj, src/yetibot/core/adapters.clj, src/yetibot/core/commands/history.clj, src/yetibot/core/handler.clj, src/yetibot/core/interpreter.clj, src/yetibot/core/parser.clj, src/yetibot/core/unparser.clj, test/yetibot/core/test/parser.clj
=> Fix history command when extra commands are processed

test/yetibot/core/test/util/config.clj
- `test/yetibot/core/test/util/config.clj`
- simple addition of tests for YB.core.util.config
=> add tests for core.util.config

test/yetibot/core/test/commands/help.clj
- `test/yetibot/core/test/commands/help.clj`
- easy win << famous last words
=> add tests for one of the more important commands YB has

test/yetibot/core/test/chat.clj
=> add tests for chat-data-structure

test/yetibot/core/test/parser.clj
- nothing earth-shattering, just saw a couple of cases not being tested
- want to get to 100% coverage before applying kibit recommendations
=> getting to 100% coverage of core.parser

.github/workflows/release.yml, .github/workflows/test.yml, src/yetibot/core/adapters/irc.clj, src/yetibot/core/adapters/mattermost.clj, src/yetibot/core/adapters/slack.clj
=> Propagate platform-specific raw-event in chat-sources
